### ISSUE TITLE
feat(device): Support other input devices than touch

### ISSUE THREAD

**Issue by tbosch** [ajoslin/angular-scrolly#7] opened 2013-07-18 10:45 UTC
Hi,
it would be great to do the scrolling also with the mousewheel or with the keys. This would result in a better experience if mobile sites are viewed on desktop browsers without touch screen. 

By the way, scrolling using the mouse right now (with click and move) is not working so well. Could you have a look into that?

Tobias

**Comment by ajoslin** [comment] 2013-07-18 13:00
Perhaps just use normal overflow scroll on desktop?

**Comment by tbosch** [comment] 2013-07-18 13:06
Yes, but it's not so easy to detect "desktop" browser. I thought adding this to your lib would make things easier...

**Comment by ajoslin** [comment] 2013-07-18 13:07
Can't we just detect the presence of touch in document?

I could try it, but it may be hard to get it to work well.  Although I think even on desktop with lists of 100-200+, fake scrolling is better performance. So it may be worth doing.

**Comment by tbosch** [comment] 2013-07-18 13:11
Well, newer "desktops" have touch and mouse / touchpad support (e.g. Chrome Pixel)...

**Comment by ajoslin** [comment] 2013-07-18 13:24
oh good point. OK, I will get mousewheel to work.

**Comment by ajoslin** [comment] 2013-07-23 14:18
I tried mousewheel last night and failed to get it to work smoothly - the problem is that there is no 'mousewheelend' event - the best I could do is check if there has been no mousewheel event since 100ms ago or so - but no matter what I set for the ms it still looks bad.

My next attempt will be just to listen to the 'scroll' event and set the transform to whatever the scroll change was.

**Comment by ajoslin** [comment] 2013-07-25 17:31
edit: not doing this approach

**Comment by tbosch** [comment] 2013-07-26 17:28
Not bad.
However, the fixed top toolbar is hoping up and down when I scroll using my mac touchpad...
Aah, didn't think this was so complicated, but apparently it is!

**Comment by ajoslin** [comment] 2013-07-26 17:30
If we are ok with no acceleration on desktop, I could go back to catching mousewheel event.  That would be more reliable.

**Comment by ajoslin** [comment] 2013-07-26 17:30
There are just so many though. mousewheel, arrow keys, spacebar, ...

**Comment by tbosch** [comment] 2013-07-26 17:34
Yes, I think so too. At least it would be accessible on the desktop, which is already a good improvement.

**Comment by ajoslin** [comment] 2013-07-29 14:14
OK, added desktopScroller service. It's landed in master.  I tested it manually but didn't have time to add unit tests this morning for it.  But it works a lot lot lot better now :-)

And there _are_ unit tests for scroller.js now.

There's simply no boundary bouncing on desktop now, but that's a lot better than trying to fake it .. since none of the desktop scroll keys have "end" events, there's no way to fake it reliably.

@tigbro could you try it in angular-jqm and see if its good? I probably won't have time until late this week.

**Comment by tbosch** [comment] 2013-07-29 15:55
Will look into it tomorrow.

**Comment by tbosch** [comment] 2013-08-01 07:18
Great work, scrolling on the desktop works fine with both, scroll wheel and keys!
You could also add a scrollbar, but I think that's just a detail. 

So I think we could close this?

**Closed as completed** 2013-08-08 11:43 UTC
